# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pygui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyGUI(object):
    def setupUi(self, PyGUI):
        PyGUI.setObjectName("PyGUI")
        PyGUI.resize(393, 288)
        self.centralwidget = QtWidgets.QWidget(PyGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 351, 61))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 30, 151, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 351, 131))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(190, 80, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(190, 40, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 220, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 220, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 220, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        PyGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PyGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 393, 21))
        self.menubar.setObjectName("menubar")
        self.menuApplication_by_Darren_Jonas_and_Finn = QtWidgets.QMenu(self.menubar)
        self.menuApplication_by_Darren_Jonas_and_Finn.setSeparatorsCollapsible(False)
        self.menuApplication_by_Darren_Jonas_and_Finn.setObjectName("menuApplication_by_Darren_Jonas_and_Finn")
        PyGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PyGUI)
        self.statusbar.setObjectName("statusbar")
        PyGUI.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuApplication_by_Darren_Jonas_and_Finn.menuAction())

        self.retranslateUi(PyGUI)
        QtCore.QMetaObject.connectSlotsByName(PyGUI)

    def retranslateUi(self, PyGUI):
        _translate = QtCore.QCoreApplication.translate
        PyGUI.setWindowTitle(_translate("PyGUI", "MainWindow"))
        self.groupBox.setTitle(_translate("PyGUI", "Input data"))
        self.label.setText(_translate("PyGUI", "Current temperature"))
        self.groupBox_2.setTitle(_translate("PyGUI", "Parameterization"))
        self.comboBox.setItemText(0, _translate("PyGUI", "Kelvin [ K ]"))
        self.comboBox.setItemText(1, _translate("PyGUI", "Celsius [ °C ]"))
        self.comboBox.setItemText(2, _translate("PyGUI", "Fahrenheit [°F ]"))
        self.label_2.setText(_translate("PyGUI", "Sampling time in ms"))
        self.label_3.setText(_translate("PyGUI", "Unit of temperature"))
        self.pushButton.setText(_translate("PyGUI", "Update"))
        self.pushButton_2.setText(_translate("PyGUI", "Start"))
        self.pushButton_3.setText(_translate("PyGUI", "Stop"))
        self.menuApplication_by_Darren_Jonas_and_Finn.setTitle(_translate("PyGUI", "Application by Darren, Jonas and Finn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyGUI = QtWidgets.QMainWindow()
    ui = Ui_PyGUI()
    ui.setupUi(PyGUI)
    PyGUI.show()
    sys.exit(app.exec_())
